language: java
services:
  - postgresql
before_script:
  - psql -c 'CREATE DATABASE "q-url-api";' -U postgres
  - psql -d "q-url-api" -c "CREATE USER dev WITH PASSWORD 'dev';" -U postgres
  - psql -d "q-url-api" -c 'GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO dev;' -U postgres
  - psql -d "q-url-api" -c 'CREATE EXTENSION IF NOT EXISTS "uuid-ossp";' -U postgres