language: java
services:
  - postgresql
deploy:
  provider: heroku
  api_key:
    secure: xqEtbl9P4PZVwuoq9Jmxuqvgu6KaXD6eXO1zp4OwsMNJb+uhxXgvRFvbrIbUmNM0s04L2asT9dMND0WB7KTeQMkAsbQdM0sjbWWyEqjZazPnzTJyRlqz9QHWB5WZkDHUgUQn5rTox+7NtqIY/kT9SnjwmGNHSoKf/tzWsY0yQOyPmy8MarQd6BY4CILJn9VblXo1d4IpTnoPya8989jB1h/XZZfZHDUZXB1PN7tskB/TlAjGreDVPhzaTrh3mhSRyCzyQhunJqQwq+xhs1+ISSMG6CuKRd49mx3+xzNtSnPcatAI/ZDxZ1fPuRWaQjHVqgbP5i2K1ZVnoJBJcRhn1iIFNUiOYpISz4g8bg6X4FEN0w4fC8TlZ6XWpTfBtU2sKOaFZdrkyiCpmBn78hXXtniwAdZqacR6W9AAs8avHja48xOSmXmxx4QKvFZkbKAwUeVS4VonxIoWR17X6Dm255XXYvS7GY9x+FZ0dbB3p8YlZzgw6y+pVH/V6zRS2A4e1Hod5YagCEfEvhe3A7MHLSdvQXpsgBMPceB1O6T2pwfmRxGg9WoUWbcLocs9eaZCVNzQdKwWbcB0DdnDur94GkW2FJGFjRTvq+LiWbVTTBxvXDl9mx5NSB0yu0S7Obtz2/5Y1nqldCe6Alhioq+BxEpEckEjup+wgzOf0pXod1Q=
before_script:
  - psql -c 'CREATE DATABASE "q-url-api";' -U postgres
  - psql -d "q-url-api" -c "CREATE USER dev WITH PASSWORD 'dev';" -U postgres
  - psql -d "q-url-api" -c 'GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO dev;' -U postgres
  - psql -d "q-url-api" -c 'CREATE EXTENSION IF NOT EXISTS "uuid-ossp";' -U postgres