language: java
services:
  - postgresql
deploy:
  provider: heroku
  api_key:
    secure: XWfFOk7U4qcU4UnWcbQTAil4HuzImZhZg/NaGfcRGfxUPSMIKwaD7MA3KvP32O9Na2aob7265KSoid7ty0pEh2JQ8yIUXnvA8kcky+BvbWZBsSDaD7d6wBRt8ay0UAY/7AGX3PxH6A/TwM7kDxHi2+SRJHYliB5L1hMVSUcw2AtxtQ4f1WVi05wDr2OH4+vq2wDCKUD+e3mZ1Ae0s9nvsu7zOgKCE5DQxm5ODU3WJ+c4bgq1uy+VyQVXE4mx/qrm3Lr0h0SfI+qzhLKoZceT3xYCnwEqzHASrhPzMl0U9d3vuOViERmRIYdquOzTZhI2NLISF7EXR8kq35dTD7gMBCzegobbGm3suq98omiOnrxsb8B3DFmB24joQbxLI80kCBji2T7ZV54i1OGR93UStPAErUlnS7qUVvV6jNCqHcfNtBu7Tlurv05BmGk10BpENhHUuJ4J/jY+iBgrjCTEBX6cFx6tyFVF5zmihcfoME1+Tb+e6zzJdXcpg3f84yE5kJsTInx/aEmlTPZZJ+56sjNDMN+6k2qJT7mpOOOCHuneCfJnS1ZjT0n8LKupZOsWWJxxitKW05Fox5B8rKvX3zNEMSpw28vkAxPBrrFi/PVkdQ09nZkFL1guP1bL8KBKWOiKRYzBFX6mECiVevY6A9T5sTQ6GnsHfPo1idCq3ns=
before_script:
  - psql -c 'CREATE DATABASE "q-url-api";' -U postgres
  - psql -d "q-url-api" -c "CREATE USER dev WITH PASSWORD 'dev';" -U postgres
  - psql -d "q-url-api" -c 'GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO dev;' -U postgres
  - psql -d "q-url-api" -c 'CREATE EXTENSION IF NOT EXISTS "uuid-ossp";' -U postgres