language: java
services:
  - postgresql
deploy:
  provider: heroku
  api_key:
    secure: DesdjfcQim9A8loCUD0dc3DoAudDQEhrAajVrVxiPJBXVcYape2ZgykNdST4ZJkHFML18l77Qb8ZUYewKoI57vuhRVRhQp5WXaGuiJjn14DGteEP1S7u/1gLrzkgeS0DdYvTmPrFUtUmqlqIzFF3VbuFBzwhJ+qJ6GPBZMkzawPKLaFTF/XN6yQeoeaOVP/IfVVZx5wdfmRaS8tQvO/RKt2SuyU4fqC6HK2zGh47q8Kwe+B7RvQsOZl3KPElqKqlhpACpT4mk4oWoQOPQMVES7m41fXWGvQlkjpP9B72vS4yvDuNkxt0hmiCUlYY24Qfbg9fFTXMdqjUbGUezTBRG4wF+p/keK+S5m25HDswHwbjB0ZW1v/auCF86MbKml/63bZd6uKe56X5c1cxMITW4HP47ARY6DSZk6/rL644Ul+rWt+0iPz9Qo6TZ95urFCS16awa+fEAs8cH/d705mJ8v5Tbh4d5RClt7pVkEOILlYybHE0lu3iSzSaaVmh1XfiZdcK7fqCOCZtiAlBuAiypyfAxHU1rF/Vk3Lm1B0Xwvv6QKPXFGMnyeElrx6vl/dc78ARAMUvq5lKtoz+9XmfkqHAreeBwCV1f4d4xIhuzK9Qj7P/Z+GZWaRXsEuGEIIdsLEV4/aCU0iU1/yTAqvXgfNtPRkMaZkdARaTn+gWE1o=
before_script:
  - psql -c 'CREATE DATABASE "q-url-api";' -U postgres
  - psql -d "q-url-api" -c "CREATE USER dev WITH PASSWORD 'dev';" -U postgres
  - psql -d "q-url-api" -c 'GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO dev;' -U postgres
  - psql -d "q-url-api" -c 'CREATE EXTENSION IF NOT EXISTS "uuid-ossp";' -U postgres