services:
  app:
    image: 'kujawad/q-url-api:latest'
    build:
      context: .
    container_name: q-url-api
    ports:
      - '8080:8080'
    expose:
      - '8080'
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    env_file:
      - .env