version: '3'
services:
  app:
    container_name: q-url-api
    build:
      context: .
      dockerfile: docker/q-url-api/Dockerfile
    image: q-url-api:latest
    depends_on:
      - db
    expose:
      - 8080
    ports:
      - 8080:8080
    networks:
      - q-url-api-network
  db:
    container_name: q-url-api-postgres
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    image: q-url-api-postgres:latest
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - q-url-api-network
networks:
  q-url-api-network:
    driver: bridge