services:
  - type: web
    name: q-url-api
    env: docker
    repo: https://github.com/kujawad/q-url-api
    region: frankfurt # optional (defaults to oregon)
    plan: free # optional (defaults to starter)
    branch: native # optional (uses repo default)
    numInstances: 1 # optional (defaults to 1)
    healthCheckPath: /actuator/health
    envVars:
      - key: SERVER_PORT
        value: 443
